services:
    db:
        image: postgres:16.4-alpine
        env_file: ./.env
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db:
